#!/bin/bash

die() {
	printf "Error: $1\n" 1>&2
	exit 1
}

usage() {
	read -r -d '' TEXT <<-EOF
	Usage: $0 -d <bd> [ -x <de> -p <pkgs> <scripts> ]
	  -d <bd>       block device to operate on
	  -x <de>       desktop environment, from: lxde (todo: add more)
	  -p <pkgs>     additional packages to install from arch repo's

	  <scripts>  additional scripts to run from in chroot following install
	EOF
	echo "$TEXT"
}

OPTIND=1
DEVICE=
DESKTOP=
PKGS=
SCRIPTS=
while getopts ":d:x:p:h" opt; do
	case $opt in
		d)
			DEVICE="$OPTARG"
			;;
		x)
			DESKTOP="$OPTARG"
			;;
		p)
			PKGS="$OPTARG"
			;;
		h)
			usage && exit 0
			;;
		:)
			echo "Option -$OPTARG requires an argument" >&2
			usage && exit 1
			;;
		\?)
			echo "Invalid options: -$OPTARG" >&2
			usage && exit 1
			;;
	esac
done
shift $((OPTIND-1))

if [[ -z "$DEVICE" ]]; then
	usage && echo && die "-d <block device> is required" || die
fi
